apiVersion: v1
kind: Namespace
metadata:
  name: rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lister
  namespace: rbac
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lister
  namespace: rbac
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lister
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lister
    spec:
      serviceAccountName: lister
      containers:
      - name: lister
        image: lister
