apiVersion: v1
kind: Namespace
metadata:
  name: greeting-syncer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeting-syncer
  namespace: greeting-syncer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: greeting-syncer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: greeting-syncer
subjects:
- kind: ServiceAccount
  name: greeting-syncer
  namespace: greeting-syncer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-syncer
  namespace: greeting-syncer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: greeting-syncer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: greeting-syncer
    spec:
      serviceAccountName: greeting-syncer
      containers:
      - name: manager
        image: greeting-syncer
