//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *FleetPolicy) DeepCopyInto(out *FleetPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

func (in *FleetPolicy) DeepCopy() *FleetPolicy {
	if in == nil {
		return nil
	}
	out := new(FleetPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *FleetPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *FleetPolicyList) DeepCopyInto(out *FleetPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FleetPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *FleetPolicyList) DeepCopy() *FleetPolicyList {
	if in == nil {
		return nil
	}
	out := new(FleetPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *FleetPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
