apiVersion: v1
kind: Namespace
metadata:
  name: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: manager
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: manager
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: manager
spec:
  selector:
    app: manager
  ports:
  - port: 8080
